### ISSUE TITLE
Music fails to play in exports

### ISSUE THREAD

**Issue by zaknafean** [AnJ95/godot-toolbox-project#5]
**Godot Version** 3.4.2

When exporting a project, music and sound effects will not play _if it was defined in the config file_.

**Steps to reproduce**
As an example, play the demo game from the editor, and all is well.
Export to windows or html5 and the title music will not play nor will the UI_SELECT or UI_BACK sound effects, and you will not get the 'coffee break' track when you pause the game, it'll fall back to a quieter version of the level theme.

In the rapid research we did during the gamejam we were in, we think this is due to a bug in Godot that is discussed here: https://github.com/godotengine/godot/issues/18390

**Workarounds**
For the gamejam we were in, we were able to get around the issue by hard coding a load(<full path to the music>) for the title and level tracks, changing this:
![image](https://user-images.githubusercontent.com/7741797/158411645-37037e58-f0ad-40e1-a7fb-340547705dcf.png)
to
![image](https://user-images.githubusercontent.com/7741797/158411724-e61cf3e0-70cd-4038-b6b9-ba1c769e4332.png)
in Level.gd

and this:
![image](https://user-images.githubusercontent.com/7741797/158412133-3d7d7c5b-9ded-47b6-9b89-319ce5a65416.png)
to
![image](https://user-images.githubusercontent.com/7741797/158412213-7a208e09-d423-49ce-8251-dd84abf51ed8.png)
in SoundMngr.gd

Similar hard coding was done in place of UI_SELECT and UI_BACK as well.

Why this worked but the 'try_load' and set thats done in Config.gd didn't is not something I'm sure of.

**Comment by zaknafean** [comment]
Seems another work around is to NOT do the **.file_exists** check in **try_load**, but obviously thats a trade off. But that seems to be the quickest fix

**Comment by zaknafean** [comment]
PR made that fixes it pretty nicely

**Comment by AnJ95** [comment]
The change made in the PR does work like a charm - I merged it.
Thanks for letting me know and especially thanks for fixing the issue!
